params:
  author:
    name: "Jacob"
    links:
      - github: "https://github.com/dewofyouryouth"
      - youtube: "https://www.youtube.com/channel/UC-rJLeLJVWLKQKnXyLkw3bw"
      - instagram: "https://www.instagram.com/yaakshore/"
      - ko-fi: "https://ko-fi.com/dewofyouryouth"
  article:
    showAuthor: true    # ensure the author box (with links) appears on posts
