params:
  author:
    name: "Jacob"
    links:
      - link: "https://dewofyouryouth.com"
      - github: "https://github.com/dewofyouryouth"
      - youtube: "https://www.youtube.com/channel/UC-rJLeLJVWLKQKnXyLkw3bw"
      - instagram: "https://www.instagram.com/yaakshore/"
      - ko-fi: "https://ko-fi.com/dewofyouryouth"
      - discord: "https://discord.com/users/dew_of_your_youth"
      - rss: "/index.xml"
  article:
    showAuthor: true    # ensure the author box (with links) appears on posts
