main:
  - name: Start Here
    url: /start/
    weight: 1
  - name: Blog
    url: /blog/
    weight: 2
  - name: Shami (Levantine)
    url: /dialects/shami/
    weight: 3
  - name: Tunisian
    url: /dialects/tunisian/
    weight: 4
  - name: Learn
    url: /learn/
    weight: 5
  - name: Tutors
    url: /tutors/
    weight: 6
  - name: About
    url: /about/
    weight: 7
footer:
  - name: Series
    url: /series/
    weight: 1
  - name: Categories
    url: /categories/
    weight: 2
  - name: Tags
    url: /tags/
    weight: 3
  - name: Jacob Shore
    url: https://jacob-shore.com
    weight: 4
